"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import sys

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv
import dj_database_url

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

def env_bool(name, default=False):
    return os.environ.get(name, str(default)).strip().lower() in ("1", "true", "yes", "on")


def env_list(name, default=""):
    return [v.strip() for v in os.environ.get(name, default).split(",") if v.strip()]


# DEBUG is OFF unless explicitly turned on. Put DEBUG=True in your local
# .env file for development - production then stays safe even if you forget
# to configure it.
DEBUG = env_bool('DEBUG', False)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', '')
if not SECRET_KEY:
    if DEBUG or 'test' in sys.argv:
        SECRET_KEY = 'django-insecure-local-development-only-key-do-not-use-in-production'
    else:
        raise ImproperlyConfigured(
            "SECRET_KEY environment variable is required when DEBUG is off. Generate one with: "
            "python -c \"import secrets; print(secrets.token_urlsafe(50))\""
        )

# In development any host is fine (Codespaces gives random hostnames). In
# production set ALLOWED_HOSTS=yourdomain.com,www.yourdomain.com
ALLOWED_HOSTS = env_list('ALLOWED_HOSTS', '*' if DEBUG else 'localhost,127.0.0.1')

# Number of reverse proxies in front of Django (Render/Railway/Heroku/Fly = 1).
# Used to read the real client IP for rate limiting. Leave 0 if unsure.
NUM_PROXIES = int(os.environ.get('NUM_PROXIES', '0'))

if not DEBUG:
    SECURE_SSL_REDIRECT = env_bool('SECURE_SSL_REDIRECT', True)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = env_bool('SECURE_HSTS_PRELOAD', False)
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
    SESSION_COOKIE_HTTPONLY = True
    X_FRAME_OPTIONS = 'DENY'


# Codespaces (and similar cloud dev environments) serve the site over HTTPS through
# a proxy, so Django needs to trust that forwarded scheme and the dynamic preview
# domain, otherwise CSRF checks fail with "Origin checking failed".
CSRF_TRUSTED_ORIGINS = env_list('CSRF_TRUSTED_ORIGINS') + ([
    'https://*.app.github.dev',
    'https://*.githubpreview.dev',
    'https://*.gitpod.io',
    'http://localhost:8000',
    'https://localhost:8000',
    'http://127.0.0.1:8000',
    'https://127.0.0.1:8000',
] if DEBUG else [])
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = env_bool('USE_X_FORWARDED_HOST', DEBUG)


# Application definition

INSTALLED_APPS = [
    'bees',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'bees.middleware.StaffTwoFactorMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'bees.middleware.NoCacheMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'bees.context_processors.cart_count',
                'bees.context_processors.wishlist_ids',
                'bees.context_processors.site_language',
                'bees.context_processors.unread_notifications',
                'bees.context_processors.compare_count',
                'bees.context_processors.site_banner',
                'bees.context_processors.brand',
                'bees.context_processors.roles',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Supabase (or any Postgres): set DATABASE_URL to the connection string from
# Supabase > Project Settings > Database > Connection string.
#   - Session pooler / direct (port 5432): persistent connections are fine.
#   - Transaction pooler (port 6543, best for serverless): connections must
#     not be reused and server-side cursors must be off - handled below.
# Without DATABASE_URL the project falls back to a local SQLite file.
DATABASE_URL = os.environ.get('DATABASE_URL', '').strip()
if DATABASE_URL and '://' not in DATABASE_URL:
    raise ImproperlyConfigured(
        "DATABASE_URL is not a valid connection string. Paste the full URI from Supabase > "
        "Project Settings > Database > Connection string, e.g. "
        "postgresql://postgres.xxxx:PASSWORD@aws-0-us-east-1.pooler.supabase.com:5432/postgres "
        "- or remove DATABASE_URL to use local SQLite."
    )
_uses_transaction_pooler = ':6543' in DATABASE_URL
DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=0 if _uses_transaction_pooler else 600,
        conn_health_checks=not _uses_transaction_pooler,
        ssl_require=DATABASE_URL.startswith('postgres') and 'localhost' not in DATABASE_URL,
    )
}
if _uses_transaction_pooler:
    DATABASES['default']['DISABLE_SERVER_SIDE_CURSORS'] = True


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
PRIVATE_MEDIA_ROOT = BASE_DIR / 'private_media'

STORAGES = {
    # Public files: product images, store logos/banners, brand logo.
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    # Private files: seller ID documents and business certificates. Never
    # served at a public URL - staff open them through /staff/seller-document/.
    'private': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
        'OPTIONS': {'location': PRIVATE_MEDIA_ROOT, 'base_url': '/staff/private-media/'},
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Tests run without `collectstatic`, so they use plain static storage.
if 'test' in sys.argv:
    STORAGES['staticfiles'] = {'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage'}

# Supabase Storage (S3-compatible). Create two buckets in Supabase > Storage:
#   - a PUBLIC bucket for product images (SUPABASE_STORAGE_BUCKET)
#   - a PRIVATE bucket for seller documents (SUPABASE_PRIVATE_BUCKET)
# and S3 access keys under Storage > Settings > S3 Connection.
SUPABASE_PROJECT_REF = os.environ.get('SUPABASE_PROJECT_REF', '')
SUPABASE_S3_ACCESS_KEY_ID = os.environ.get('SUPABASE_S3_ACCESS_KEY_ID', '')
SUPABASE_S3_SECRET_ACCESS_KEY = os.environ.get('SUPABASE_S3_SECRET_ACCESS_KEY', '')
SUPABASE_S3_REGION = os.environ.get('SUPABASE_S3_REGION', 'us-east-1')
SUPABASE_STORAGE_BUCKET = os.environ.get('SUPABASE_STORAGE_BUCKET', 'media')
SUPABASE_PRIVATE_BUCKET = os.environ.get('SUPABASE_PRIVATE_BUCKET', 'private')
USE_SUPABASE_STORAGE = bool(SUPABASE_PROJECT_REF and SUPABASE_S3_ACCESS_KEY_ID and SUPABASE_S3_SECRET_ACCESS_KEY)

if USE_SUPABASE_STORAGE:
    _s3_common = {
        'endpoint_url': f'https://{SUPABASE_PROJECT_REF}.storage.supabase.co/storage/v1/s3',
        'region_name': SUPABASE_S3_REGION,
        'access_key': SUPABASE_S3_ACCESS_KEY_ID,
        'secret_key': SUPABASE_S3_SECRET_ACCESS_KEY,
        'addressing_style': 'path',
        'signature_version': 's3v4',
        'file_overwrite': False,
    }
    STORAGES['default'] = {
        'BACKEND': 'storages.backends.s3.S3Storage',
        'OPTIONS': {
            **_s3_common,
            'bucket_name': SUPABASE_STORAGE_BUCKET,
            'querystring_auth': False,
            # Public object URLs: https://<ref>.supabase.co/storage/v1/object/public/<bucket>/<path>
            'custom_domain': f'{SUPABASE_PROJECT_REF}.supabase.co/storage/v1/object/public/{SUPABASE_STORAGE_BUCKET}',
        },
    }
    STORAGES['private'] = {
        'BACKEND': 'storages.backends.s3.S3Storage',
        'OPTIONS': {
            **_s3_common,
            'bucket_name': SUPABASE_PRIVATE_BUCKET,
            'querystring_auth': True,
            'querystring_expire': 300,
        },
    }

# Public address of the store, used for links in emails sent outside a
# request (order shipped / delivered ...). Defaults to the first host in
# ALLOWED_HOSTS, e.g. https://19bees.netlify.app
SITE_URL = os.environ.get('SITE_URL', '').strip().rstrip('/')

# Stripe (card payments). See bees/payments.py.
STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_KEY', '')
STRIPE_PUBLISHABLE_KEY = os.environ.get('STRIPE_PUBLISHABLE_KEY', '')
STRIPE_WEBHOOK_SECRET = os.environ.get('STRIPE_WEBHOOK_SECRET', '')
STORE_CURRENCY = os.environ.get('STORE_CURRENCY', 'usd').lower()
# Optional: send Stripe API calls through a relay instead of directly to
# api.stripe.com. Needed on PythonAnywhere's free plan, which blocks
# api.stripe.com but allows *.supabase.co - see deploy/supabase/stripe-relay.
STRIPE_API_BASE = os.environ.get('STRIPE_API_BASE', '').strip().rstrip('/')
if STRIPE_API_BASE and not STRIPE_API_BASE.startswith('https://'):
    raise ImproperlyConfigured("STRIPE_API_BASE must start with https://")

# Seller commission tiers: (lifetime sales at or above, % points off the
# base commission rate). Checked top to bottom.
COMMISSION_TIERS = [(25000, 5), (5000, 2)]

FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'

EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
if EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.gmail.com'
    EMAIL_PORT = 587
    EMAIL_TIMEOUT = 10
    EMAIL_USE_TLS = True
    DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Any SMTP provider (SendGrid, Mailgun, Postmark, Amazon SES, Resend...)
# can be used instead of Gmail by setting EMAIL_HOST/EMAIL_PORT too.
if os.environ.get('EMAIL_HOST'):
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.environ['EMAIL_HOST']
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
    EMAIL_USE_TLS = env_bool('EMAIL_USE_TLS', True)
    EMAIL_TIMEOUT = 10
    DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)

# Shared cache for rate limiting / verification codes. Set REDIS_URL when
# running more than one app process (e.g. several gunicorn workers).
if os.environ.get('REDIS_URL'):
    CACHES = {'default': {'BACKEND': 'django.core.cache.backends.redis.RedisCache', 'LOCATION': os.environ['REDIS_URL']}}

# Error monitoring (Sentry). Only activates if SENTRY_DSN is set as an
# environment variable - without it, this is a no-op, so nothing breaks
# for local development or before you've created a Sentry project.
# Get a free DSN at https://sentry.io -> Create Project -> Django.
SENTRY_DSN = os.environ.get('SENTRY_DSN', '')
if SENTRY_DSN:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[DjangoIntegration()],
        # Sends 100% of errors, and samples 10% of requests for performance
        # tracing (lower this further if the Sentry free-tier quota fills up).
        traces_sample_rate=0.1,
        send_default_pii=False,
        environment=os.environ.get('SENTRY_ENVIRONMENT', 'production' if not DEBUG else 'development'),
    )
