# Generated by Django 6.0.7 on 2026-07-29 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('skincare', 'Skin care'), ('haircare', 'Hair care'), ('grocery', 'Grocery'), ('fashion', 'Fashion'), ('electronics', 'Electronics'), ('3d-printers', '3D printers'), ('pasta-tools', 'Pasta, Noodle & Pizza Tools'), ('sim-devices', 'SIM devices'), ('screen-protector', 'Screen protector'), ('casserole-pot', 'Casserole pot'), ('table-lamp', 'Table lamp'), ('hoodies', 'Hoodies & Sweatshirts'), ('toy-boxes', 'Toy boxes and organizers'), ('sneakers', 'Sneakers'), ('education', 'Education'), ('dress-up-kits', 'Dress-Up Kits'), ('microphones', 'Microphones'), ('leashes', 'Leashes and harnesses'), ('donate-education', 'Donate to education'), ('coloring-drawing', 'Coloring & Drawing'), ('lotion-cream', 'Lotion, Cream and Scrubs')], default='grocery', max_length=30),
        ),
    ]
