# Generated by Django 6.0.7 on 2026-08-04 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bees', '0008_alter_profile_referral_code_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seller_name',
            field=models.CharField(default='19Bees Mall', max_length=100),
        ),
    ]
