# Generated by Django 6.0.7 on 2026-08-05 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bees', '0010_selleraccount_product_seller_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('site_name', models.CharField(default='19Bees', max_length=100)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='approval_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending review'), ('rejected', 'Rejected')], default='approved', max_length=20),
        ),
        migrations.AddField(
            model_name='review',
            name='is_verified_purchase',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='selleraccount',
            name='admin_note',
            field=models.CharField(blank=True, help_text='Internal note, e.g. reason for rejection or requested info', max_length=255),
        ),
        migrations.AddField(
            model_name='selleraccount',
            name='bank_details',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='selleraccount',
            name='brand_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='selleraccount',
            name='business_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='selleraccount',
            name='business_certificate',
            field=models.FileField(blank=True, null=True, upload_to='seller_docs/certificates/'),
        ),
        migrations.AddField(
            model_name='selleraccount',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='selleraccount',
            name='cnic',
            field=models.CharField(blank=True, max_length=30, verbose_name='CNIC / National ID'),
        ),
        migrations.AddField(
            model_name='selleraccount',
            name='country',
            field=models.CharField(blank=True, default='Pakistan', max_length=100),
        ),
        migrations.AddField(
            model_name='selleraccount',
            name='full_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='selleraccount',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='seller_docs/ids/'),
        ),
        migrations.AddField(
            model_name='selleraccount',
            name='organization_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='selleraccount',
            name='product_categories',
            field=models.CharField(blank=True, help_text='Comma-separated categories the store will sell', max_length=255),
        ),
        migrations.AddField(
            model_name='selleraccount',
            name='store_banner',
            field=models.ImageField(blank=True, null=True, upload_to='seller_docs/banners/'),
        ),
        migrations.AddField(
            model_name='selleraccount',
            name='store_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='selleraccount',
            name='store_logo',
            field=models.ImageField(blank=True, null=True, upload_to='seller_docs/logos/'),
        ),
        migrations.AddField(
            model_name='selleraccount',
            name='tax_info',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='selleraccount',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('refunded', 'Refunded')], default='requested', max_length=20)),
                ('admin_note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='bees.orderitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_reviews', to='bees.selleraccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('seller', 'user')},
            },
        ),
    ]
