# Generated by Django 6.1 on 2026-08-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bees', '0011_sitesettings_product_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='selleraccount',
            name='total_paid_out',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total amount already paid to this seller (recorded by admin after each payout).', max_digits=12),
        ),
    ]
