# Generated by Django 6.1 on 2026-08-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bees', '0014_returnrequest_refund_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='banner_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='banner_link',
            field=models.CharField(blank=True, help_text='Optional URL the banner links to (e.g. a sale category page).', max_length=300),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='banner_text',
            field=models.CharField(blank=True, help_text="Shown as a site-wide announcement bar at the top of every page, e.g. 'Eid Sale: 20% off everything!'. Leave blank to hide it.", max_length=200),
        ),
    ]
