# Generated by Django 6.1 on 2026-08-14 01:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bees', '0016_organizationmember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='approval_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending review'), ('rejected', 'Rejected')], db_index=True, default='approved', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('skincare', 'Skin care'), ('haircare', 'Hair care'), ('grocery', 'Grocery'), ('fashion', 'Fashion'), ('electronics', 'Electronics'), ('3d-printers', '3D printers'), ('pasta-tools', 'Pasta, Noodle & Pizza Tools'), ('sim-devices', 'SIM devices'), ('screen-protector', 'Screen protector'), ('casserole-pot', 'Casserole pot'), ('table-lamp', 'Table lamp'), ('hoodies', 'Hoodies & Sweatshirts'), ('toy-boxes', 'Toy boxes and organizers'), ('sneakers', 'Sneakers'), ('education', 'Education'), ('dress-up-kits', 'Dress-Up Kits'), ('microphones', 'Microphones'), ('leashes', 'Leashes and harnesses'), ('donate-education', 'Donate to education'), ('coloring-drawing', 'Coloring & Drawing'), ('lotion-cream', 'Lotion, Cream and Scrubs')], db_index=True, default='grocery', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_flash_sale',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller_name',
            field=models.CharField(db_index=True, default='19Bees Mall', max_length=100),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('refunded', 'Refunded')], db_index=True, default='requested', max_length=20),
        ),
        migrations.AlterField(
            model_name='selleraccount',
            name='account_type',
            field=models.CharField(choices=[('individual', 'Individual seller'), ('organization', 'Organization / Business')], db_index=True, default='individual', max_length=20),
        ),
        migrations.AlterField(
            model_name='selleraccount',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='bees_notifi_user_id_b6c86b_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='bees_order_status_67b294_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='bees_order_user_id_04964a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['approval_status', 'category'], name='bees_produc_approva_8f47aa_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['approval_status', 'is_flash_sale'], name='bees_produc_approva_83d896_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['stock'], name='bees_produc_stock_917e3f_idx'),
        ),
    ]
