# Generated by Django 6.1 on 2026-08-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bees', '0017_alter_order_created_at_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Coupon stops working after this date. Leave blank for no expiry.', null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='min_order_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cart total must be at least this much for the code to apply. 0 = no minimum.', max_digits=10),
        ),
        migrations.AddField(
            model_name='coupon',
            name='per_user_limit',
            field=models.PositiveIntegerField(default=1, help_text='Maximum number of times a single customer can use this code.'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='usage_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of times this code can be used in total, across all customers. Leave blank for unlimited.', null=True),
        ),
    ]
