# Generated by Django 6.1 on 2026-08-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bees', '0019_chatthread_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='jazzcash_txn_ref',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('not_applicable', 'Not applicable (COD)'), ('pending', 'Awaiting payment'), ('paid', 'Paid'), ('failed', 'Failed')], db_index=True, default='not_applicable', max_length=20),
        ),
    ]
