# Generated by Django 6.1.2 on 2026-10-06 23:54

import bees.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def forwards(apps, schema_editor):
    ReturnRequest = apps.get_model("bees", "ReturnRequest")
    ReturnRequest.objects.filter(refund_method="wallet_credit").update(refund_method="store_credit")

    # Seller verification documents used to live in the public media folder.
    # Move any local copies into the private folder so they stop being
    # reachable at a public URL.
    import os
    import shutil
    from django.conf import settings
    if getattr(settings, "USE_SUPABASE_STORAGE", False):
        return
    for folder in ("seller_docs/certificates", "seller_docs/ids"):
        src = os.path.join(settings.MEDIA_ROOT, folder)
        if os.path.isdir(src):
            dst = os.path.join(settings.PRIVATE_MEDIA_ROOT, folder)
            os.makedirs(dst, exist_ok=True)
            for name in os.listdir(src):
                shutil.move(os.path.join(src, name), os.path.join(dst, name))


def backwards(apps, schema_editor):
    ReturnRequest = apps.get_model("bees", "ReturnRequest")
    ReturnRequest.objects.filter(refund_method="store_credit").update(refund_method="wallet_credit")


class Migration(migrations.Migration):

    dependencies = [
        ("bees", "0020_order_jazzcash_txn_ref_order_payment_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name_plural": "Addresses"},
        ),
        migrations.RemoveField(
            model_name="order",
            name="jazzcash_txn_ref",
        ),
        migrations.AddField(
            model_name="address",
            name="country",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name="address",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="address",
            name="state",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="country",
            field=models.CharField(
                blank=True,
                help_text="ISO 3166-1 alpha-2 country code, e.g. US",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="currency",
            field=models.CharField(default="usd", max_length=3),
        ),
        migrations.AddField(
            model_name="order",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="order",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="order",
            name="state",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="State / Province / Region"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="stripe_payment_intent",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="stripe_session_id",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="tax_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="accent_color",
            field=models.CharField(
                default="#F2B33D",
                help_text="Accent colour (badges, highlights, announcement bar). Use a light/bright colour - dark text sits on it. Hex, e.g. #F2B33D",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#[0-9A-Fa-f]{6}$", "Enter a 6-digit hex colour like #0E3B43."
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="allow_cash_on_delivery",
            field=models.BooleanField(
                default=True,
                help_text="Show 'Cash on delivery' at checkout. Card payments appear automatically once Stripe keys are set.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="company_address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="facebook_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="favicon_url",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="free_shipping_threshold",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Orders at or above this subtotal ship free. 0 = disabled.",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_image_url",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_subtitle",
            field=models.CharField(
                default="Shop trusted brands and independent sellers. Secure checkout, fast shipping and easy returns.",
                max_length=240,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_title",
            field=models.CharField(
                default="Everyday essentials, beautifully curated", max_length=120
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="instagram_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="logo_file",
            field=models.ImageField(
                blank=True,
                help_text="Or upload a logo here (PNG/SVG/JPG).",
                null=True,
                upload_to="branding/",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="logo_url",
            field=models.CharField(
                blank=True,
                help_text="Full URL of your logo (upload it to Supabase Storage or any image host). Leave blank to show the store name as text.",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="primary_color",
            field=models.CharField(
                default="#0E3B43",
                help_text="Main brand colour (buttons, footer). Use a dark colour so white text stays readable. Hex, e.g. #0E3B43",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#[0-9A-Fa-f]{6}$", "Enter a 6-digit hex colour like #0E3B43."
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="shipping_flat_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Flat shipping fee per order. 0 = free shipping.",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="show_language_menu",
            field=models.BooleanField(
                default=False,
                help_text="Show the English / Urdu / Roman Urdu language switcher.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="support_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="support_phone",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="tagline",
            field=models.CharField(
                default="Thoughtfully chosen products, delivered worldwide.",
                max_length=160,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="twitter_url",
            field=models.URLField(blank=True, verbose_name="X / Twitter URL"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="youtube_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("card", "Card (Stripe)"), ("cod", "Cash on delivery")],
                default="card",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("not_applicable", "Not applicable (COD)"),
                    ("pending", "Awaiting payment"),
                    ("paid", "Paid"),
                    ("failed", "Failed"),
                    ("refunded", "Refunded"),
                ],
                db_index=True,
                default="not_applicable",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="seller_name",
            field=models.CharField(
                db_index=True, default="Official Store", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="returnrequest",
            name="refund_method",
            field=models.CharField(
                choices=[
                    ("original_payment", "Original payment method"),
                    ("store_credit", "Store credit"),
                ],
                default="original_payment",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="selleraccount",
            name="business_certificate",
            field=models.FileField(
                blank=True,
                null=True,
                storage=bees.models._private_storage,
                upload_to=bees.models.seller_cert_path,
            ),
        ),
        migrations.AlterField(
            model_name="selleraccount",
            name="cnic",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="National ID / Passport number"
            ),
        ),
        migrations.AlterField(
            model_name="selleraccount",
            name="country",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="selleraccount",
            name="id_document",
            field=models.FileField(
                blank=True,
                null=True,
                storage=bees.models._private_storage,
                upload_to=bees.models.seller_id_path,
            ),
        ),
        migrations.AlterField(
            model_name="selleraccount",
            name="store_banner",
            field=models.ImageField(
                blank=True, null=True, upload_to=bees.models.seller_banner_path
            ),
        ),
        migrations.AlterField(
            model_name="selleraccount",
            name="store_logo",
            field=models.ImageField(
                blank=True, null=True, upload_to=bees.models.seller_logo_path
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="banner_text",
            field=models.CharField(
                blank=True,
                help_text="Shown as a site-wide announcement bar at the top of every page, e.g. 'Summer sale: 20% off everything'. Leave blank to hide it.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="site_name",
            field=models.CharField(
                default="Lumen Market", max_length=100, verbose_name="Store name"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="tax_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Applied to the discounted subtotal at checkout. 0 = no tax line.",
                max_digits=5,
            ),
        ),
        migrations.RunPython(forwards, backwards),
    ]
