# Generated by Django 6.1.2 on 2026-10-07 10:33

import django.db.models.deletion
from django.db import migrations, models


def backfill(apps, schema_editor):
    """Existing sales: link them to the product's seller and record the
    seller's base commission rate at that time."""
    from decimal import Decimal, ROUND_HALF_UP
    OrderItem = apps.get_model("bees", "OrderItem")
    for item in OrderItem.objects.select_related("product__seller_account").filter(product__seller_account__isnull=False):
        seller = item.product.seller_account
        rate = Decimal(seller.commission_rate or 0)
        item.seller_account = seller
        item.commission_rate = rate
        item.commission_amount = (item.price * item.quantity * rate / 100).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)
        item.save(update_fields=["seller_account", "commission_rate", "commission_amount"])


class Migration(migrations.Migration):

    dependencies = [
        ("bees", "0021_international_launch"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cod_fallback",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="commission_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="commission_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="seller_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Empty for the store's own products (no commission).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sold_items",
                to="bees.selleraccount",
            ),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
