# Generated by Django 6.1.2 on 2026-10-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bees", "0022_commission_and_pay_later"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="delivery_days",
            field=models.PositiveSmallIntegerField(
                default=5,
                help_text="Usual delivery time in business days. Used for the 'Arrives by' date customers see and get emailed.",
            ),
        ),
    ]
