# Generated by Django 6.1.2 on 2026-10-07 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def mark_old_referrals_rewarded(apps, schema_editor):
    # Under the old rules referrers were rewarded at sign-up already.
    Profile = apps.get_model("bees", "Profile")
    Profile.objects.exclude(referred_by="").update(referral_rewarded=True)



class Migration(migrations.Migration):

    dependencies = [
        ("bees", "0023_delivery_days"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="credit_returned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="credit_used",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="order",
            name="delivered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="referral_rewarded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="store_credit",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="question",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="returnrequest",
            name="card_refund_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="returnrequest",
            name="credit_refund_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="return_days",
            field=models.PositiveSmallIntegerField(
                default=14,
                help_text="How many days after delivery customers can request a return.",
            ),
        ),
        migrations.RunPython(mark_old_referrals_rewarded, migrations.RunPython.noop),
    ]
