# Generated by Django 6.1.2 on 2026-10-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bees", "0024_audit_fixes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={
                "ordering": ["-is_default", "id"],
                "verbose_name_plural": "Addresses",
            },
        ),
        migrations.AddField(
            model_name="address",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
