# Generated by Django 6.1.2 on 2026-10-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bees", "0025_account_settings"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShippingZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. United States, Europe, Rest of world",
                        max_length=60,
                    ),
                ),
                (
                    "countries",
                    models.TextField(
                        help_text="Two-letter country codes separated by commas (US, CA), or * for every other country."
                    ),
                ),
                (
                    "fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "free_over",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Orders at or above this amount (after discounts) ship free. Empty = never free.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "delivery_days",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Usual delivery time in business days. Empty = store default.",
                        null=True,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
