# Generated by Django 6.1.2 on 2026-10-07 18:49

import secrets

from django.db import migrations, models


def fill_tokens(apps, schema_editor):
    Order = apps.get_model("bees", "Order")
    for order in Order.objects.filter(access_token="").only("id"):
        Order.objects.filter(pk=order.pk).update(access_token=secrets.token_urlsafe(16)[:32])



class Migration(migrations.Migration):

    dependencies = [
        ("bees", "0027_variants_stock_alerts"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="access_token",
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.RunPython(fill_tokens, migrations.RunPython.noop),
    ]
