# Generated by Django 6.1.2 on 2026-10-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bees", "0028_guest_checkout"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="cart_reminder_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="cart_reminders",
            field=models.BooleanField(
                default=True, help_text="Email a reminder about items left in the cart."
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="cart_updated_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="saved_cart",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
