# Generated by Django 6.1.2 on 2026-10-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bees", "0029_saved_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="backup_codes",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="profile",
            name="totp_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="totp_last_step",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profile",
            name="totp_secret",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="require_staff_2fa",
            field=models.BooleanField(
                default=True,
                help_text="Staff must use an authenticator app code to open the store admin.",
                verbose_name="Require two-step sign-in for staff",
            ),
        ),
    ]
