# Generated by Django 6.1.2 on 2026-10-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bees", "0030_two_step"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="stripe_last_webhook",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
