# Generated by Django 6.1.2 on 2026-10-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bees", "0031_stripe_last_webhook"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="extra",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="is_auto",
            field=models.BooleanField(default=False),
        ),
    ]
