# Generated by Django 6.1.2 on 2026-10-07 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill(apps, schema_editor):
    """Existing orders were handled before sellers got order alerts, and
    payouts recorded before this change become one history entry each."""
    Order = apps.get_model("bees", "Order")
    SellerAccount = apps.get_model("bees", "SellerAccount")
    Payout = apps.get_model("bees", "Payout")
    Order.objects.update(sellers_notified=True)
    for seller in SellerAccount.objects.filter(total_paid_out__gt=0):
        Payout.objects.create(
            seller=seller, amount=seller.total_paid_out, status="paid",
            note="Payouts recorded before payout history was added", paid_at=seller.created_at,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("bees", "0032_chat_assistant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="sellers_notified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="selleraccount",
            name="vacation_message",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="selleraccount",
            name="vacation_mode",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Payout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("paid", "Paid"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="requested",
                        max_length=20,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bank", "Bank transfer"),
                            ("paypal", "PayPal"),
                            ("wise", "Wise"),
                            ("payoneer", "Payoneer"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Transfer reference"
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payouts",
                        to="bees.selleraccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
