# Generated by Django 6.1.2 on 2026-10-08 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bees", "0033_seller_center"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SellerPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="0 = free plan.",
                        max_digits=8,
                        verbose_name="Price per month",
                    ),
                ),
                (
                    "commission_discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Percentage points taken off the seller's commission, e.g. 3 turns 10% into 7%.",
                        max_digits=5,
                    ),
                ),
                (
                    "product_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Leave empty for unlimited products.",
                        null=True,
                    ),
                ),
                (
                    "badge",
                    models.BooleanField(
                        default=False,
                        help_text="Show a 'Pro seller' badge on the store and its products.",
                    ),
                ),
                (
                    "perks",
                    models.TextField(
                        blank=True,
                        help_text="Extra benefits shown on the plan card, one per line.",
                    ),
                ),
                (
                    "highlight",
                    models.BooleanField(default=False, verbose_name="Most popular"),
                ),
                ("position", models.PositiveSmallIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["position", "price"],
            },
        ),
        migrations.AddField(
            model_name="selleraccount",
            name="plan_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="selleraccount",
            name="plan_reminder_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="commission_individual",
            field=models.DecimalField(
                decimal_places=2,
                default=10,
                help_text="Taken from each sale by new individual sellers. Existing sellers keep their own rate.",
                max_digits=5,
                verbose_name="Commission for individual sellers (%)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="commission_organization",
            field=models.DecimalField(
                decimal_places=2,
                default=20,
                help_text="Taken from each sale by new business / organization sellers.",
                max_digits=5,
                verbose_name="Commission for organizations (%)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="setup_completed",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.CreateModel(
            name="PlanPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plan_name", models.CharField(max_length=40)),
                ("months", models.PositiveSmallIntegerField(default=1)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Waiting for payment"),
                            ("paid", "Paid"),
                            ("failed", "Not completed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[("card", "Card"), ("manual", "Recorded by staff")],
                        default="card",
                        max_length=10,
                    ),
                ),
                (
                    "stripe_session_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_payments",
                        to="bees.selleraccount",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="bees.sellerplan",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="selleraccount",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sellers",
                to="bees.sellerplan",
            ),
        ),
    ]


def seed(apps, schema_editor):
    SiteSettings = apps.get_model("bees", "SiteSettings")
    # Stores that already exist are set up; only fresh installs see the wizard.
    SiteSettings.objects.all().update(setup_completed=True)
    SellerPlan = apps.get_model("bees", "SellerPlan")
    if not SellerPlan.objects.exists():
        SellerPlan.objects.create(
            name="Starter", price=0, commission_discount=0, product_limit=50, position=1,
            perks="Seller Center with sales reports\nPayouts to your bank\nEmail alerts for every order")
        SellerPlan.objects.create(
            name="Pro", price=19, commission_discount=3, product_limit=500, badge=True, highlight=True, position=2,
            perks="Everything in Starter\n'Pro seller' badge on your store and products\nPriority product review")
        SellerPlan.objects.create(
            name="Business", price=49, commission_discount=5, product_limit=None, badge=True, position=3,
            perks="Everything in Pro\nUnlimited products\nLowest commission\nPriority support")


Migration.operations.append(migrations.RunPython(seed, migrations.RunPython.noop))
