# Generated by Django 6.1.2 on 2026-10-08 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bees", "0034_seller_plans_setup"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Three letters, e.g. EUR", max_length=3, unique=True
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        help_text="Shown before the amount, e.g. €", max_length=6
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="How many of this currency one unit of the store currency buys.",
                        max_digits=14,
                    ),
                ),
                ("decimals", models.PositiveSmallIntegerField(default=2)),
                ("active", models.BooleanField(default=False)),
                ("position", models.PositiveSmallIntegerField(default=0)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Currencies",
                "ordering": ["position", "code"],
            },
        ),
        migrations.AddField(
            model_name="coupon",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="coupon",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_coupons",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="purpose",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Store coupon"),
                    ("referral_welcome", "Referral welcome"),
                    ("referral_reward", "Referral reward"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="tracking_url",
            field=models.CharField(
                blank=True,
                help_text="Optional. Leave empty to build the link from the courier and tracking number.",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="bulk_min_qty",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="bulk_percent",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="flash_sale_ends",
            field=models.DateTimeField(
                blank=True,
                help_text="When the deal ends. A countdown is shown until then; empty = no end date.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="selleraccount",
            name="top_seller",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="selleraccount",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shippingzone",
            name="per_item_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Added for every item after the first. 0 = same fee for any number of items.",
                max_digits=10,
                verbose_name="Each extra item",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="referral_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Customers share a link; friends get a welcome discount and the customer is rewarded after the friend's first delivered order.",
                verbose_name="Referral program on",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="referral_friend_percent",
            field=models.PositiveSmallIntegerField(
                default=10, verbose_name="Friend's welcome discount (%)"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="referral_reward_percent",
            field=models.PositiveSmallIntegerField(
                default=10, verbose_name="Reward for the customer who shared (%)"
            ),
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_message_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("buyer_unread", models.PositiveIntegerField(default=0)),
                ("seller_unread", models.PositiveIntegerField(default=0)),
                ("buyer_emailed_at", models.DateTimeField(blank=True, null=True)),
                ("seller_emailed_at", models.DateTimeField(blank=True, null=True)),
                ("reported", models.BooleanField(db_index=True, default=False)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seller_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="bees.product",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="bees.selleraccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_message_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_seller", models.BooleanField(default=False)),
                ("body", models.TextField(max_length=2000)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="bees.conversation",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="bees.product",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="conversation",
            constraint=models.UniqueConstraint(
                fields=("buyer", "seller"), name="one_conversation_per_buyer_seller"
            ),
        ),
    ]


# Starting rates against USD. They are approximate and the currencies start
# switched off: the owner presses "Update rates now" (or edits them) and
# turns on the ones they want.
START = [
    ("EUR", "€", "0.86", 2), ("GBP", "£", "0.75", 2), ("AED", "AED ", "3.6725", 2), ("SAR", "SAR ", "3.75", 2),
    ("CAD", "CA$", "1.38", 2), ("AUD", "A$", "1.52", 2), ("INR", "₹", "87", 0), ("PKR", "Rs ", "281", 0),
]


def seed(apps, schema_editor):
    from django.conf import settings
    Currency = apps.get_model("bees", "Currency")
    if getattr(settings, "STORE_CURRENCY", "usd").lower() != "usd" or Currency.objects.exists():
        return
    for pos, (code, symbol, rate, decimals) in enumerate(START, start=1):
        Currency.objects.create(code=code, symbol=symbol, rate=rate, decimals=decimals, active=False, position=pos)


Migration.operations.append(migrations.RunPython(seed, migrations.RunPython.noop))
