# Generated by Django 6.1 on 2026-08-08 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daraz', '0012_selleraccount_total_paid_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier_name',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_delivery',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='fulfillment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('packed', 'Packed'), ('handed_to_courier', 'Handed to courier'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='loyalty_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
