# Generated by Django 6.1 on 2026-08-08 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daraz', '0013_order_courier_name_order_estimated_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='refund_method',
            field=models.CharField(choices=[('original_payment', 'Original payment method'), ('wallet_credit', '19Bees wallet credit')], default='original_payment', max_length=20),
        ),
    ]
